spring:
  application:
    name: gateway-server

server:
  port: 10250

#  cloud:
#    gateway:
#      default-filters:
#        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
#      globalcors:
#        corsConfigurations:
#          '[/**]':
#            allowedOrigins: "*"
#            allowedMethods:
#              - GET
#              - POST
#              - PUT
#              - DELETE
#            allowedHeaders: "*"
#      routes:
#        - id: auth-service
#          uri: lb://AUTH-SERVER
#          predicates:
#            - Path=/auth/**
#          filters:
#            - StripPrefix=1
#
#        - id: shop-service
#          uri: lb://SHOP-SERVER
#          predicates:
#            - Path=/shop/**
#          filters:
#            - StripPrefix=1
#
#  main:
#    allow-bean-definition-overriding: true

eureka:
  client:
    service-url:
      defaultZone: http://admin:1234@localhost:10252/eureka,http://admin:1234@localhost:10253/eureka
    fetch-registry: true
    register-with-eureka: true
  instance:
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: health,info
