spring:
  data:
    redis:
      host: s4.java21.net
      port: 6379
      database: 295
      password: ${REDIS_PASSWORD}
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL}
    fetch-registry: true
    register-with-eureka: true
  instance:
    prefer-ip-address: true
gateway:
  whitelist:
    - /auth/**
    - /shop/**
