spring:
  application:
    name: ink3-gateway
  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
            allowedHeaders: "*"
      routes:
        - id: shop-service
          uri: lb://SHOP-SERVICE
          predicates:
            - Path=/api/**
          filters:
            - StripPrefix=1

        - id: front-service
          uri: lb://FRONT-SERVICE
          predicates:
            - Path=/front/**
          filters:
            - StripPrefix=1

        - id: auth-service
          uri: lb://AUTH-SERVICE
          predicates:
            - Path=/auth/**
          filters:
            - StripPrefix=1
  main:
    allow-bean-definition-overriding: true
management:
  endpoints:
    web:
      exposure:
        include: health,info
