spring:
  application:
    name: ink3-gateway
  config:
    import: optional:configserver:https://ink3.shop/config/
  rabbitmq:
    host: ${RABBITMQ_HOST}
    port: ${RABBITMQ_PORT}
    username: ${RABBITMQ_USERNAME}
    password: ${RABBITMQ_PASSWORD}
  cloud:
    bus:
      enabled: true
