server:
  port: 10250

jwt:
  secret: prod-secret
  cookie-name: jwt

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL}
    fetch-registry: true
    register-with-eureka: true
  instance:
    prefer-ip-address: true
