jwt:
  secret: prod-secret
  cookie-name: jwt

eureka:
  client:
    service-url:
      defaultZone: http://admin:1234@ink3.shop:10252/eureka/
    fetch-registry: true
    register-with-eureka: true
  instance:
    prefer-ip-address: true
