spring:
  config:
    activate:
      on-profile: dev

jwt:
  secret: dev-secret
  cookie-name: jwt

eureka:
  client:
    service-url:
      defaultZone: http://admin:1234@localhost:10252/eureka/eureka
    fetch-registry: true
    register-with-eureka: true
  instance:
    prefer-ip-address: true