name: CI

# 워크플로 트리거: main 브랜치로의 push 혹은 PR
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  # build:
  #   runs-on: ubuntu-latest

  #   steps:
  #     # 1. 코드 체크아웃
  #     - name: Checkout code
  #       uses: actions/checkout@v3

  #     # 2. JDK 설정 (Temurin 17)
  #     - name: Set up JDK 21
  #       uses: actions/setup-java@v3
  #       with:
  #         distribution: temurin
  #         java-version: 21
  #         cache: maven

  #     # 3. Maven 의존성 캐시
  #     - name: Cache Maven packages
  #       uses: actions/cache@v3
  #       with:
  #         path: ~/.m2/repository
  #         key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
  #         restore-keys: |
  #           ${{ runner.os }}-m2-

  #     # 4. Maven 빌드 및 테스트
  #     - name: Build & test with Maven
  #       run: mvn clean verify -B


  # #실행테스트
  # smoke-test:
  #   needs: build
  #   runs-on: ubuntu-latest

  #   steps:
  #     # 1. 빌드 결과를 받아오려면 다시 체크아웃 (artifact 공유 설정이 없다면)
  #     - name: Checkout code
  #       uses: actions/checkout@v3

  #     # 2. JDK 설정 (Temurin 21)
  #     - name: Set up JDK 21
  #       uses: actions/setup-java@v3
  #       with:
  #         distribution: temurin
  #         java-version: 21

  #     # 3. 패키징
  #     - name: Package application
  #       run: mvn package -DskipTests -B

  #     # 4. 백그라운드로 애플리케이션 실행
  #     - name: Run application in background
  #       run: |
  #         nohup java -jar target/*.jar > app.log 2>&1 & echo $! > app.pid

  #     # 5. 기동 대기
  #     - name: Wait for application to start
  #       run: sleep 30

  #     # 6. 헬스 체크 엔드포인트 호출
  #     - name: Check health endpoint
  #       run: curl --fail http://localhost:8080/actuator/health

  #     # 7. 애플리케이션 종료
  #     - name: Stop application
  #       run: kill $(cat app.pid)

  deploy:
    # needs: smoke-test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 21

      - name: Package application
        run: mvn package -DskipTests -B

      - name: Test SSH Only
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: s1.java21.net
          port: 8822
          username: be9-team3
          key: -----BEGIN OPENSSH PRIVATE KEY-----
b3BlbnNzaC1rZXktdjEAAAAABG5vbmUAAAAEbm9uZQAAAAAAAAABAAACFwAAAAdzc2gtcn
NhAAAAAwEAAQAAAgEAp7aJfeDf1NTD42jFJ5pBe5Dc5CtNrFS7WiZZ7xFs49hF/4yI4lBn
hSk0qbs032GNnpGOLiNMUxzJ9SMCWW0gDu8Pj45HigqaEPhmsNQYFRFST4Zv7Yj2CdV01X
CHCpi0EWcB6/3ZQCWEJ0tDiPsQOaJ734hSafifMa67N75d7kqEX+fr6GlV5mipXQOYQ95M
wj4PnrD0IxxvbGswRDZ7KeX4nO0gKPvaPDhogpBY5N7/8xzdk20qb3xxX9TBNOk5vfkHdZ
OtF6W9jJ4BN4bhPYhdUQ+09ko2DTkQJ5cRRrkEJuLRJPXCIHJtU8rvs7Akn5Vm8h9n/Pdu
nCtPJDrRtrlIHIpoXNy3F4++kfGZImntFTQn7XKMgy2kzNu78uaHksFnWszh+ddt1iYoBM
6P42yJTsKgxwlW7NLCz60dze7bFUnYNxHDD/2z9qNOOV9h4lQFQJt6WkCOn/LGGR3hUOz6
LR9AxIoSzlC1Ac0TTkeCgP8DAsKEdv5Cg1eP0lZD3QMWiXZymo8iuBIJIr1CotRtq5pclA
WUAzhNkYnwZtOcJIkSQE9o5tUbvaq8nR+XFRzQqbpPpAiWoTpMcNYn6AxWT5S6tf1Uf3zp
lyRJZRM3Kqls907SYsyR3+w55UubRvCg8UTO+79/4oSZYG0woSvTY+fXbl6XVTjwnmXClb
sAAAdIZoJ3e2aCd3sAAAAHc3NoLXJzYQAAAgEAp7aJfeDf1NTD42jFJ5pBe5Dc5CtNrFS7
WiZZ7xFs49hF/4yI4lBnhSk0qbs032GNnpGOLiNMUxzJ9SMCWW0gDu8Pj45HigqaEPhmsN
QYFRFST4Zv7Yj2CdV01XCHCpi0EWcB6/3ZQCWEJ0tDiPsQOaJ734hSafifMa67N75d7kqE
X+fr6GlV5mipXQOYQ95Mwj4PnrD0IxxvbGswRDZ7KeX4nO0gKPvaPDhogpBY5N7/8xzdk2
0qb3xxX9TBNOk5vfkHdZOtF6W9jJ4BN4bhPYhdUQ+09ko2DTkQJ5cRRrkEJuLRJPXCIHJt
U8rvs7Akn5Vm8h9n/PdunCtPJDrRtrlIHIpoXNy3F4++kfGZImntFTQn7XKMgy2kzNu78u
aHksFnWszh+ddt1iYoBM6P42yJTsKgxwlW7NLCz60dze7bFUnYNxHDD/2z9qNOOV9h4lQF
QJt6WkCOn/LGGR3hUOz6LR9AxIoSzlC1Ac0TTkeCgP8DAsKEdv5Cg1eP0lZD3QMWiXZymo
8iuBIJIr1CotRtq5pclAWUAzhNkYnwZtOcJIkSQE9o5tUbvaq8nR+XFRzQqbpPpAiWoTpM
cNYn6AxWT5S6tf1Uf3zplyRJZRM3Kqls907SYsyR3+w55UubRvCg8UTO+79/4oSZYG0woS
vTY+fXbl6XVTjwnmXClbsAAAADAQABAAACAAN6omSFly8TkNK1WC2nogcdrK9hBJX4FgDb
Pc9bRa5+TIluEWLcdyFIhwqkUwb1P5pT+6aSXeF1fe0DYmeXf2w/4ktAkNRYvvRuKrctVy
iMuO/kYosDZdMzZd6NnIeIPmgEAoKyO+D8Rj8IbSi4yI/hgn9TFR6UpTzDGqgf31PzoMZa
icbC9KC4eBbxXaW+xUncPre0hQP7cYZGvPQVSz3FwwACXUHsY40PQH/A3c81nwqchS4rPA
+e/b0WrUFbOzLpKRHz08njSsjReEX+GssLeqAVWtQnGvLwRZkEpbuZV/A0kVEadgH1TbZI
xess0r2qvD12kFIrkdRUg6pFPBdtKGQifcUjhlIVVJHkaQVgqV1pleUtN1AWzMaEAuVfyE
CSqSabA4lxGSDMKLBv66xKl1v+2DHqzHAFnk0jKzZzq/8/6T05Pk10O79oI1FOlWA99hUb
qgajpx42ki3FzXSSwnZkpkrGzRWlLgY7leEkH5JI8zTPS5DikAgc5fGDJfMhPOqjxWGbcy
juKxep913oP28RCW8gHEem9DY9o6HqrE7v6TgLBrhi5vxdWOq9vOF79SE15rsrTWFPV8W5
A61CVvrVjJPGHeYtFnZiyW9b1sT9DIu4aUnO2PrQThD/oPOXIAe3DEXP2UN14QgHim0Ojd
JztQrxUFS0aQNazRcJAAABAQCB9U/RmHdGL+yCKOCD4lxjk29yhrtZ68o7p2VFoVkCv1uO
onx/rNXPJpdaSFl6S8JzbBw8j4dD50CR8QM8gYKpXHGl3N7Zfn5z/FXweeq0bHQrv6EwJk
wtMLeYH80AIVaImen0pTFL1Mi47kBixIeRAv1VpceZ6M973hVr0Ecjwv/eajkI1AM6OSxt
UTrBsAOM4dEFKLyPr0yuYID6hWOlCfaCPV+ng3AzsOwoTKqUtUxv76eik/VJODZz7JoKQu
Hju39BWzNdj6ws0gIOQ4WgBe3k/2RA73zmc+CLT4EbkQITDzW7LdgV9Fa5uY9rSWp3uM4c
kz6LMlYBXPYDKCz7AAABAQDcrpUgNCjUUxDt6oOGcfEdMxmbWZm6IPPLpPXJZaTD6j1TQ4
Xjn8Zgt0oJ30VTXF7Wyf09l1SlADqOlLERmG0iAGNZ/FZ3qvpyBKSxtLJ2SbQ1ToK0iNlH
HXiJRqxEws8wIeHU4VBRlOuTfbVIg96dVCz1nMdYSSFLMrt2wN7JwpEvqpX58zN/To3B+0
9Gdl0aUR+2U+TLQFVVxYlJeGAb1CVSoxr7RGh0INMg2ZJwbZaSb5oLW6Oiz70t2/hPNodD
9OT44vENLxgFhOiLmyt4/qhHGeUwhrX/QPIVefp4hmUMwMKzKHVYTfeR6wQOFuyzV7H0ga
REfG4KswKszXg5AAABAQDCjcyLdSTRmgyJCZZIta9V0EhvOhT+eK8XRJsjBMp6DuibSnpm
XDIGqKHmVmHHcZ5VOYMBYEzTj1DO5lPPJQmjD29jeuAKUZLzHsUdDklCaRb9Ooq7Iyi4VZ
ezPUP9UylJyLrvGrybMICtRbh9YjNQCYgxamuGyId7VtUqtROLGZUKffUNNKsqbG6a/rL4
cJeGE0KlVBHkGeoZKlBmh704ujrdJf+HB4LgA/+o/42e8ecUeqOXPNy1I1PD7TXQNlcU+b
jYBdfTfcILF5OHG5o+xlXKQxu63oLg8JS3m5yMGaSVJEi6g88o8jZuZhGx9nlArHcBdX2V
TISOzMOVePWTAAAAEWh1bjM0NzhAZ21haWwuY29tAQ==
-----END OPENSSH PRIVATE KEY-----
          script: echo "✅ SSH 연결 성공"

      - name: Copy JAR to server (SSH key auth)
        uses: appleboy/scp-action@v0.1.5
        with:
          host: ${{ secrets.SSH_IP }}
          port: ${{ secrets.SSH_PORT }}
          username: ${{ secrets.SSH_ID }}
          key: ${{ secrets.SSH_KEY }}
          source: "target/*.jar"
          target: "~/app/"

      - name: Restart app on server
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.SSH_IP }}
          port: ${{ secrets.SSH_PORT }}
          username: ${{ secrets.SSH_ID }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            mkdir -p ~/app
            pkill -f 'java -jar' || true
            mv ~/app/*.jar ~/app/app.jar
            nohup java -jar ~/app/app.jar > ~/app/app.log 2>&1 &
            
